### ISSUE TITLE
Deploy Error - Your Apple ID account is attached to other iTunes providers

### ISSUE THREAD

**Issue by yadits** [bitrise-io/steps-deploy-to-itunesconnect-deliver#45] opened 2018-04-12 09:47 UTC
I get an error on “Your Apple ID account is attached to other iTunes providers. You will need to specify which provider you intend to submit content to by using the -itc_provider command. Please contact us if you have questions or need help. (1627)”.
I don’t understand at all.

I added Team ID and Team Name. In Application Loader it works perfectly. Please help!

**Comment by viktorbenei** [comment] 2018-04-13 11:49
Hi @yadits ,

This seems to be a duplicate of https://discuss.bitrise.io/t/deploy-to-itunes-connect-error/4774

I'll close this here, please contribute to the discussion at https://discuss.bitrise.io/t/deploy-to-itunes-connect-error/4774 ! Thanks and Happy Building! :)

**Comment by yadits** [comment] 2018-04-14 11:15
Why did you close this? I'm am the one who opened the discussion in Bitrise and was told to open an issue here. I know that that I'm not using the same username - since it was already taken.
Anyway, I need an answer this still doesn't work!

**Comment by godrei** [comment] 2018-04-16 13:14
Hi @yadits ,
sorry for the inconveniences!
Could you please have a look at my answer on discuss: https://discuss.bitrise.io/t/deploy-to-itunes-connect-error/4774/11?u=godreikrisztian

**Comment by yadits** [comment] 2018-04-16 13:16
It works, thanks a lot. I needed to write --itc_provider TEAM_ID

**Comment by viktorbenei** [comment] 2018-04-16 15:05
Thanks for reporting @yadits ! :)

**Comment by trapacska** [comment] 2018-05-23 10:49
Thanks for the info!

Just closing this issue as it is resolved now. Feel free to open a new issue if you still encounter any issues!

**Closed by trapacska** 2018-05-23 10:49 UTC
