### ISSUE TITLE
Password/AppPassword required?

### ISSUE THREAD

**Issue by Panda-ref** [bitrise-io/steps-deploy-to-itunesconnect-deliver#37] opened 2018-01-19 17:40 UTC
Hi there. Need your help.
According to https://support.apple.com/en-us/HT204397, paragraph 

> App-specific passwords are single-use passwords for your Apple ID that let you sign in to your account and securely access the information you store in iCloud from a third-party app. For example, use app-specific passwords with Microsoft Outlook, Mozilla Thunderbird, or other mail, contacts, and calendar services not provided by Apple. App-specific passwords maintain a high level of security and help ensure your Apple ID password won’t be collected or stored by any third-party apps you use.
The whole idea of using app-specific passwords is to ensure you are not revealing your apple id password.

It seems to me that Password field shouldn't be required in case you use AppPassword, but now it has this `input.ValidateIfNotEmpty` check that fails the build. My thoughts are that one of Password/AppPassword should be provided to the step config at a time otherwise I don't understand how should it work. Currently you can't use AppPassword like it was intended to be used with this step.

I would appreciate any kind of feedback. I might be completely wrong and missing something important. Thanks in advance.

P.S.
https://github.com/bitrise-io/steps-deploy-to-itunesconnect-deliver/blob/master/main.go#L340
Some strange `log.Printf` nesting.

**Comment by godrei** [comment] 2018-01-24 14:40
Hi @Panda-ref ,

thanks for the report of the log.Printf nesting.

Regarding to your App-specific password question: before i merged the PR which added this feature i tested the step and it seemed both passwords are required in case of two factor auth. The step prints the deliver command which being called, you can use that command to test it. Please let me know if you are able to use the deliver tool to deploy using only the app specific password.

**Comment by godrei** [comment] 2018-01-26 08:57
I'll close this issue, but if you need more info/help just let us know and we'll reopen it!

**Closed by godrei** 2018-01-26 08:57 UTC

**Comment by kristallvic** [comment] 2018-03-24 18:24
We also have that problem. In case the password is set - step fails on 2FA.

**Comment by viktorbenei** [comment] 2018-03-26 11:15
Hi @kristallvic can you please create a separate issue? Please also include the build URL, so that we can check the config & the logs!

**Comment by arash01** [comment] 2018-09-06 01:14
Why would you guys close this important issue without any solution?!
We have the same problem..

**Comment by viktorbenei** [comment] 2018-09-06 14:11
@arash01 as mentioned previously, please create a new ticket explaining the issue you face, preferably by creating it at https://discuss.bitrise.io/c/issues/build-issues and filling out the template there.

**Comment by viktorbenei** [comment] 2018-09-06 14:12
We need those additional information / context to be able to help efficiently :)

**Comment by viktorbenei** [comment] 2018-09-06 14:14
@arash01 alternatively, as @kristallvic mentioned you can switch to another step which uses Xcode tools directly (I'd suggest our **Deploy to iTunes Connect - Application Loader** step - https://www.bitrise.io/integrations/steps/deploy-to-itunesconnect-application-loader ). This step uses `deliver` which is maintained by https://fastlane.tools

**Comment by viktorbenei** [comment] 2018-11-19 17:48
Glad to hear @seanperez29 ! 😉

**Comment by jjblumenfeld** [comment] 2018-12-27 02:34
Hi,
Are there any differences in functionality between the 2 steps? 
`Deploy to iTunes Connect - Application Loader` vs. `Deploy to iTunes Connect with Deliver`

**Comment by fehersanyi-bitrise** [comment] 2019-01-02 12:55
Hy @jjblumenfeld 
the first one deploys to testflight the later is to the app store and asks for review.

**Comment by Tallyb** [comment] 2019-03-08 16:54
Application loader only uploads the app. I believe deliver is also creating a new version for submission, as well as upload screenshots and metadata. 
We also have the problem with running deliver when the account has 2FA.

**Comment by fehersanyi-bitrise** [comment] 2019-03-11 18:52
Hello @Tallyb 

the issue with the deliver step is that it is secretly (like in scooby doo) a fastlane deliver lane.
and unfortunately they we not yet able to overcome the 2fa enforcement so that step is currently broken 😕 and because there is no official API solution to do this, we kind of depending on them, well at least there is no point writing the exact same code for the same usage twice. Until this issue is not sorted out, or the official API does not come out that would let us handle it our way unfortunately we will not be able do do much 😢

**Comment by Tallyb** [comment] 2019-03-13 18:58
It seems weird, as deliver can skip 2fa with app specific password, no?
Seems that the issue is that app specific password is not overriding
password as it is in the apploader deliver.

**Comment by fehersanyi-bitrise** [comment] 2019-03-18 09:30
Hy @Tallyb as far as we know, currently you need both passwords in the step for it to work properly, and right now, a tooling engineer is working on it so there will be an update on the step this week if everything goes well.
